### ISSUE TITLE
Svargrond keywords to add

### ISSUE THREAD

**Issue by s2ward** [s2ward/tibia#444]
Several NPCs will likely repsond to `barbarian test`, gathering these and inserting them would make the transcripts more complete.  

Something that could maybe work as well:  

"ice dragons"
"santa claus"

**Comment by BrunoBrockweldAlves** [comment]
branch: [feature/Svargrond_Keywords](https://github.com/s2ward/tibia/tree/feature/Svargrond_Keywords)
Npcs done:
- [ ] Bertha
- [ ] Buddel
- [ ] Captain Breezelda
- [ ] Captain Haba
- [ ] Dankwart
- [ ] Eirik
- [ ] Fynn
- [ ] Gelidrazah's Thirst
- [ ] Halvar
- [ ] Hawkyr
- [ ] Iskan
- [ ] Iyad
- [ ] Janz
- [ ] Jessica
- [ ] Kjesse
- [ ] Lurik
- [ ] Nelly
- [ ] Nomad
- [ ] Rashid
- [ ] Robert
- [ ] Romir
- [ ] Sirik
- [ ] Sven
- [ ] Thorwulf

**Comment by BrunoBrockweldAlves** [comment]
PR #716
