### ISSUE TITLE
Insert kingsday keywords 

### ISSUE THREAD

**Issue by s2ward** [s2ward/tibia#471]
Player: hi
Trimegis: These stupid Kingsday festivities are the worst idea I've ever seen. Especially because drunk mundanes run through MY room all the time. I prefer to hide in the execution archives.
Player: kingsday
King Tibianus: There are numerous good reasons for celebrations and to please my loyal subjects with a few happy days.
Player: kingsday
Dog Lady: Woof. Woof!
Noodles: Wooooof! <wiggle> <wiggle> <wiggle>
Player: hi
Bozo: Hello, hello, hello and happy Kingsday! How may I entertain you today? I've prepared some special jokes for this day!
Player: jokes
Bozo: I know some 'royal' jokes! Come on, ask me about the king.
Player: king
Bozo: Kings sometimes found that uprisings were a.... peasant surprise.
Bozo: What do you call a mean Ancient Egyptian leader? Say? Say? Un-fair-oh!
Bozo: The king never let any of his personal musicians go swimming immediately after eating for fear that they would get.... minstrel cramps! Think about this for a while.
Bozo: Royal chairs are rarely throne out! Hehehehe come on, that's funny!
Bozo: It is difficult to escape being a peasant because resistance is feudal!
Bozo: Countess Sorrow recently started to think about her count-less opportunities. Get it? Get it? Hahahah!
Bozo: Queen Eloise was recently caught gambling. She had a royal flush! Hahahahaha!
Bozo: Kings worry about a receding heir line! Hahahaha!
Bozo: The people stand up for royalty. The queen sits down for royal TEA. Ah, not one of my best ones, I admit.
Bozo: Queen Eloise told King Tibianus that he was a royal pain in the butt. Mwhihihihi!
Player: kingsday
Lynda: I don't care about worldly celebrations.
Player: hail general
Harkath Bloodblade: Salutations, commoner Player. Please excuse me, but I have a lot to do on this special day. (idle)
Player: kingsday
Grof, the guard: Yes, today is Kingsday. Us guards have to keep an extra eye open.
Player: hi
Sam: Welcome to my shop and happy Kingsday, Player!
Player: hi
Frodo: Hello and happy Kingsday, Player! Feel free to take a seat and have something to drink. There are many free drinks available in the city, but of course you can also still buy better quality from me.
Player: hi
Aruda: Ooooh I love Kingsday! People are so generous on this day.
Player: hi
Quero: Interested in some instruments for the Kingsday party? Come on, make some noise!
Player: hi
Xodet: Oh, please come in, Player. If you need magical equipment such as runes or wands, just ask me for a trade. Sorry, no special offers on Kingsday. Don't know why everyone keeps asking me about it.
Player: hi
Hanna: Oh, do you wish to buy a special something for Kingsday? Have a look at my offers in gems and jewellery!
Player: hi 
Todd: Uhm oh hello Player... not so loud please... it's what? Kingsday? Feels like any other day with a hangover... what do you want?

Player: hi / rebellion?
Gamel: Shh. Especially on Kingsday it's important not too attract too much attention.

Player: hi
Benjamin: Hello and have a good Kingsday, Player. Ask me for a trade if you want to buy something. I can also explain the mail system.

Player: hi
Galuna: Happy Kingsday, Player! What do you need? Distance weapons? I sell lots of them.
Player: hi
Muriel: They've forced me to put up some decoration in the sorcerer's guild, can you imagine that? Bah. Distracts me from teaching spells.
Player: hi
Suzy: Welcome to the Tibian bank, Player! And happy Kingsday. May your fortune grow and prosper.
Player: hi
Wyat: HAIL TO KING TIBIANUS! On Kingsday, all of us have to work hard to uphold law and order.
Player: hi
Partos: And once again, I'll miss Kingsday. Well, at least I get some company here with all those drunk fools cursing the king and ending up in a cell.
Player: hi
Henricus: Greetings, fellow believer Player! There is no reason to pause the inquisition, even on Kingsday.
Player: hi
Robin: Have a good Kingsday, Player. Don't drink too much!
Player: kingsday
Marvik: Don't get distracted from your real tasks.
Player: hi
Turvy: Happy Kingsday, Player! Can I be of any assistance? Just tell me if you'd like to trade weapons or armor.
Player: hi
Gamon: Happy Kingsday, Player! Need to buy furniture? You've come to the right place!
Player: hi
Topsy: Happy Kingsday, Player! How can I help you? If you need magical equipment such as runes or wands, just ask me for a trade.

**Comment by BrunoBrockweldAlves** [comment]
Pull Request #719
